# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2a858361e309e3eb341264ee2df6bfec00fdf46d71a4712c3881f5086cdc870212a47ddce1bc1b3adb9862eb29b9cf25b076d6d6ef563149c0d05e5bd8f8e74

test:
  secret_key_base: 880f731f88c31cae3702fd8c3bff549353a251a6ea5afe12a68066c498e70d548f7f6aa5343083e8a83ed0193fc836fc7d4bd9f657f89ee9069ee6f66c680b89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
